<div id="nsnmn-main-footer">
	<ul>
	    <li><a href="<?php echo $this->baseUrl('buying-faq.html');?>">Συνήθεις Ερωτήσεις</a>|</li>
	    <li><a href="<?php echo $this->baseUrl('terms-conditions.html');?>">Όροι και Προϋποθέσεις</a>|</li>
	    <li><a href="#">© <?php echo date('Y')?> Νικ. Ι. Θεοχαράκης ΑΕ - Nissan</a>|</li>
	</ul>
</div>
<!--
<ul>
	<li><a href="#" target="_blank">Επικοινωνία</a>|</li>
	<li><a href="#">Συνήθεις Ερωτήσεις</a>|</li>
	<li><a href="#">Sitemap</a>|</li>
	<li><a href="#">Glossary</a>|</li>
	<li><a href="#">All Nissan Websites</a>|</li>
	<li><a href="#">Όροι &amp; Προϋποθέσεις</a>|</li>
	<li><a href="#">Cookies</a>|</li>
	<li><a href="#">© 2015 Νικ. Ι. Θεοχαράκης ΑΕ - Nissan</a>|</li>
</ul>
-->