<div class="page headerPage">
 <!--[if IE 7]> <div class="no-js ie7 oldie" lang="en" id="nissan-main-nav"> <![endif]-->
 <!--[if IE 8]> <div class="no-js ie8 oldie" lang="en" id="nissan-main-nav"> <![endif]-->
 <!--[if IE 9]> <div class="no-js ie9" lang="en" id="nissan-main-nav"> <![endif]--> 
 <div class="fashion no-js" lang="en" id="nissan-main-nav">
  <div role="banner" id="nsnmn">
   <div class="nsnmn-logo">
    <a href="<?php echo $this->baseUrl('/');?>">
     <img width="89" height="84" src="<?php echo $this->baseUrl('skin/images/mainheadernissanlogo.png');?>" alt="Nissan - Νικ. Ι. Θεοχαράκης ΑΕ"/>
     <span>ΕΠΙΣΤΡΟΦΗ ΣΤΗΝ ΑΡΧΙΚΗ ΣΕΛΙΔΑ</span>
    </a>
   </div>
   <div class="nsnmn-nav" role="nav">
    <ul id="nsnmn-nav-nissan">
     <?php echo $this->layout()->render('/navigations/nav_vehicles'); //01 ?>
     <?php echo $this->layout()->render('/navigations/nav_offers_finance'); //02 ?>
     <?php echo $this->layout()->render('/navigations/nav_buying'); //03 ?>
     <?php echo $this->layout()->render('/navigations/nav_business_fleet'); //04 ?>  
     <?php echo $this->layout()->render('/navigations/nav_mynissan'); //07 ?>
     <?php echo $this->layout()->render('/navigations/epektash'); //02 ?>
     <?php echo $this->layout()->render('/navigations/nav_company'); //06 ?>
     <?php echo $this->layout()->render('/navigations/nav_contactus'); //08 ?>
     <?php echo $this->layout()->render('/navigations/nav_test_drive'); ?>
     <?php echo $this->layout()->render('/navigations/nav_network'); //04 ?>
     <?php echo $this->layout()->render('/navigations/nav_independent-repairers'); //04 ?>
     <?php //echo $this->layout()->render('/navigations/nissan_lottery'); //04 ?>    
    </ul>    	
   </div> <!-- end #nav-nissan -->
   
  </div> <!-- end #nsmn -->
  <div class="containerfloater">
    <div class="floating"><img src="<?php echo $this->baseUrl('skin/images/logo2.png'); ?>"></div>
    <div>
    </div>
</div>
  <div class="container1">
  	    <nav role="navigation" class="navbar navbar-inverse">
	        <div class="navbar-header">
	            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
	                <span class="sr-only">Toggle navigation</span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	                <span class="icon-bar"></span>
	            </button>
	            <a href="#" class="navbar-brand">ΝΙΚ.Ι.ΘΕΟΧΑΡΑΚΗΣ Α.Ε</a>
	        </div>
	        <div id="navbarCollapse" class="collapse navbar-collapse">
	            <ul class="nav navbar-nav">
	                <li class="dropdown">
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">ΜΟΝΤΕΛΑ <b class="caret"></b></a>
	                    <ul role="menu" class="dropdown-menu">
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/micra.html'); ?>">MICRA</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/note.html'); ?>">NOTE</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/pulsar.html'); ?>">PULSAR</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/juke.html'); ?>">JUKE</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/juke-nismo.html'); ?>">JUKE-NISMO</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/qashqai.html'); ?>">QASHQAI</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/xtrail.html'); ?>">X-TRAIL</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/370z.html'); ?>">370Z</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/370z-roadster.html'); ?>">370Z-ROADSTER</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/gtr.html'); ?>">GTR</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/city-cars/evalia.html'); ?>">EVALIA</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/commercial/np300.html'); ?>">NAVARA</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/commercial/atleon.html'); ?>">ATLEON</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/commercial/nv200.html'); ?>">NV200</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/commercial/cabstar.html'); ?>">CABSTAR</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('vehicles/commercial/nv400.html'); ?>">NV400</a></li>
	                    </ul>
	                </li>
	                <li class="dropdown">
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">ΠΡΟΣΦΟΡΕΣ<b class="caret"></b></a>
	                    <ul role="menu" class="dropdown-menu">
	                        <li>
	                        	<a href="<?php echo $this->baseUrl('free-roadside-assistance.html'); ?>"><span>ΔΩΡΕΑΝ ΟΔΙΚΗ ΒΟΗΘΕΙΑ ΓΙΑ ΕΝΑ ΕΤΟΣ</span></a>
	                        </li>
	                        <li>
					          <a href="<?php echo $this->baseUrl('all-clear-service.html'); ?>"><span>ALL CLEAR SERVICE</span></a>
					        </li>
	                    </ul>
	                </li>
	                <li class="dropdown">
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">ΑΓΟΡΑΖΩ <b class="caret"></b></a>
	                    <ul role="menu" class="dropdown-menu">
	                        <li><a href="<?php  echo $this->baseUrl('buying.html'); ?>">ΠΡΙΝ ΤΗΝ ΑΓΟΡΑ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('buying-insurance.html'); ?>">ΑΣΦΑΛΙΣΤΙΚΗ ΚΑΛΥΨΗ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('buying-funding.html'); ?>">ΧΡΗΜΑΤΟΔΟΤΗΣΗ</a></li>
	                        <!--<li><a href="<?php  echo $this->baseUrl('buying-leasing.html'); ?>">ΧΡΟΝΟΜΙΣΘΩΣΗ</a></li>-->
	                        <li><a href="<?php  echo $this->baseUrl('buying-faq.html'); ?>">ΣΥΝΗΘΕΙΣ ΕΡΩΤΗΣΕΙΣ</a></li>
	                    </ul>
	                </li>
	                <li class="dropdown">
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">ΤΟ NISSAN MOY <b class="caret"></b></a>
	                    <ul role="menu" class="dropdown-menu">
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan.html'); ?>">ΤΟ NISSAN MOY</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-warranty.html'); ?>">ΕΓΓΥΗΣΗ NISSAN</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-car-care.html'); ?>">ΦΡΟΝΤΙΔΑ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-service-care.html'); ?>">ΠΡΟΓΡΑΜΜΑΤΑ ΣΥΝΤΗΡΗΣΗΣ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-parts-n-accessories.html'); ?>">ΑΝΤΑΛΛΑΚΤΙΚΑ & ΑΞΕΣΟΥΑΡ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-service-advice.html'); ?>">ΣΥΜΒΟΥΛΕΣ ΓΙΑ SERVICE</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-european-service-nissan-program.html'); ?>">ΠΡΟΓΡΑΜΜΑ ΕΞΥΠΗΡΕΤΗΣΗΣ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('my-nissan-faq.html'); ?>">ΣΥΝΗΘΕΙΣ ΕΡΩΤΗΣΕΙΣ</a></li>
	                    </ul>
	                </li>
	                <li class="dropdown">
	                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">ΕΤΑΙΡΙΑ<b class="caret"></b></a>
	                    <ul role="menu" class="dropdown-menu">
	                        <li><a href="<?php  echo $this->baseUrl('about-nic-j-theocarakis.html'); ?>">ΝΙΚ. Ι. ΘΕΟΧΑΡΑΚΗΣ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('about-history.html'); ?>">ΙΣΤΟΡΙΑ</a></li>
	                        <li><a href="<?php  echo $this->baseUrl('about-environment.html'); ?>">ΠΕΡΙΒΑΛΛΟΝ</a></li>
	                    </ul>
	                </li>
	                <li>
	                    <a href="<?php  echo $this->baseUrl('contact-us.html'); ?>">ΕΠΙΚΟΙΝΩΝΙΑ<b class="caret"></b></a>
	                </li>
	                <li>
	                    <a href="<?php  echo $this->baseUrl('/tools/testdrive.html'); ?>">ΚΛΕΙΣΤΕ ΕΝΑ TEST-DRIVE<b class="caret"></b></a>
	                </li>
	                <li class="dropdown">
	                    <a href="<?php  echo $this->baseUrl('network/map.html'); ?>">ΕΞΟΥΣΙΟΔΟΤΗΜΕΝΟ ΔΙΚΤΥΟ<b class="caret"></b></a>
	                </li>
	                <li>
	                    <a href="<?php  echo $this->baseUrl('independent-repairers.html'); ?>">ΑΝΕΞΑΡΤΗΤΟΙ ΕΠΙΣΚΕΥΑΣΤΕΣ<b class="caret"></b></a>
	                </li>
	            </ul>
	        </div>
	    </nav>
	</div>
  
 </div> <!-- end #nissan-main-nav -->
 
</div> <!-- end .headerPage -->