<li class="" data-tracking-zone="mainheadertab6" id="nsmn-tools">
  <a href="#"><span>ΠΡΟΣΦΟΡΕΣ</span></a>
   <div class="nsmn-layer" id="nsmn-tools-list" style="width: 216px; top: 31px;">
      <div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="<?php echo $this->baseUrl('free-roadside-assistance.html'); ?>"><span>ΔΩΡΕΑΝ ΟΔΙΚΗ ΒΟΗΘΕΙΑ ΓΙΑ ΕΝΑ ΕΤΟΣ</span></a>
          </li>
          <li>
            <a href="<?php echo $this->baseUrl('all-clear-service.html'); ?>"><span>ALL CLEAR SERVICE</span></a>
          </li>
		</ul>
      </div>
       <a class="btn-close" href="#">
       	<img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>">
       </a>
    </div>
</li>