<li id="nsmn-business-fleet">
 <a href="#"><span>ΕΤΑΙΡΙΚΕΣ ΠΩΛΗΣΕΙΣ</span></a>
 <div id="nsmn-business-fleet-list" class="nsmn-layer">
     <div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="<?php echo $this->baseUrl('fleet-department.html'); ?>"><span>FLEET SALES ΤΜΗΜΑ</span></a>
          </li>
		</div>
       <a class="btn-close" href="#">
       	<img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>">
       </a>
    </div>
</li>