<li id="nsmn-buying">
 <a href="#"><span>ΑΓΟΡΑΖΩ</span></a>
 <div id="nsmn-buying-list" class="nsmn-layer">
 <div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="<?php  echo $this->baseUrl('buying.html'); ?>"><span>ΠΡΙΝ ΤΗΝ ΑΓΟΡΑ</span></a>
          </li>
		  <li>
            <a href="<?php  echo $this->baseUrl('buying-insurance.html'); ?>"><span>ΑΣΦΑΛΙΣΤΙΚΗ ΚΑΛΥΨΗ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('buying-funding.html'); ?>"><span>ΧΡΗΜΑΤΟΔΟΤΗΣΗ</span></a>
          </li>
		 <li>
            <a href="<?php  echo $this->baseUrl('buying-faq.html'); ?>"><span>ΣΥΝΗΘΕΙΣ ΕΡΩΤΗΣΕΙΣ</span></a>
         </li>
       </div>
       <a class="btn-close" href="#">
       	<img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>">
       </a>
</div>

</li>