<li id="nsmn-company">
 <a href="#"><span>ΕΤΑΙΡΙΑ</span></a>
 <div id="nsmn-company-list" class="nsmn-layer">
 <div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="<?php  echo $this->baseUrl('about-nic-j-theocarakis.html'); ?>"><span>ΝΙΚ. Ι. ΘΕΟΧΑΡΑΚΗΣ</span></a>
          </li>
		  <li>
            <a href="<?php  echo $this->baseUrl('about-history.html'); ?>"><span>ΙΣΤΟΡΙΑ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('about-environment.html'); ?>"><span>ΠΕΡΙΒΑΛΛΟΝ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('about-deltia-tupou.html'); ?>"><span>ΔΕΛΤΙΑ ΤΥΠΟΥ</span></a>
          </li>
       </div>
       <a class="btn-close" href="#">
       	<img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>">
       </a>
</div>
</li>