<li id="nsmn-contactus">
 <a href="<?php echo $this->baseUrl('contact-us.html'); ?>"><span>ΕΠΙΚΟΙΝΩΝΙΑ</span></a>
<!-- 
<div id="nsmn-contactus-list" class="nsmn-layer">
	<div class="nsmn-picto-list">
		<ul>
          <li><a href="#"><span>ΕΠΙΚΟΙΝΩΝΙΑ</span></a></li>
          <li><a href="#"><span>ΥΠΗΡΕΣΙΕΣ ΠΕΛΑΤΗ</span></a></li>
          <li><a href="#"><span>ΣΥΝΗΘΕΙΣ ΕΡΩΤΗΣΕΙΣ</span></a></li>
          <li><a href="#"><span>ΔΙΑΜΟΡΦΩΣΤΕ ΤΟ ΔΙΚΟ ΣΑΣ NISSAN</span></a></li>
          <li><a href="#"><span>ΚΑΤΕΒΑΣΤΕ ΤΟ ΦΥΛΑΔΙΟ</span></a></li>
          <li><a href="#"><span>ΕΞΟΥΣΙΟΔΟΤΗΜΕΝΟ ΔΙΚΤΥΟ</span></a></li>
        </ul>
    </div>
    <a class="btn-close" href="#"><img alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>"></a>
</div>
-->
</li>