<li id="nsmn-innovation">
 <a href="#"><span>ΕΜΠΕΙΡΙΑ NISSAN</span></a>
 <div id="nsmn-innovation-list" class="nsmn-layer" style="width: 433px; top: 31px;">
  <div class="nsmn-picto-list">
   <ul>
    <li><a href="#"><span>NISSAN ΙΣΤΟΡΙΕΣ</span></a></li>
    <li><a href="#"><span>NISSAN UEFA CHAMPION LEAGUE</span></a></li>
    <li><a href="#"><span>ΚΑΙΝΟΤΟΜΙΕΣ NISSAN</span></a></li>
    <li><a href="#"><span>NISSAN CONNECT</span></a></li>
   </ul>
  </div>
<div class="nsmn-picto-list">
  <ul>
    <li>
     <a href="#" target="_blank"><img class="img-picto" src="http://media.nissan.eu/content/dam/pes/default/common/pictos/socialtools/youtube_404.png"
     style="display: inline;"><span>YOUTUBE – NISSAN GR</span></a>
    </li>
    <li>
      <a href="https://www.facebook.com/NissanGreece?fref=ts" target="_blank"><img class="img-picto" src="http://media.nissan.eu/content/dam/pes/default/common/pictos/socialtools/facebook_404.png"
      style="display: inline;"><span>FACEBOOK - NISSAN GR</span></a>
    </li>
    <li>
     <a href="https://twitter.com/NissanGreece" target="_blank"><img class="img-picto" src="http://media.nissan.eu/content/dam/pes/default/common/pictos/socialtools/twitter_404.png"
     style="display: inline;"><span>TWITTER</span></a>
    </li>
  </ul>
</div>
<a class="btn-close" href="#"><img width="22" height="30" alt="close" src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>"></a>
</div>
</li>