<?php
$infoText = 'Σύμφωνα με την πολιτική της εταιρείας περί συνεχούς βελτίωσης των προϊόντων της, η NISSAN διατηρεί το δικαίωμα να αλλάξει';
$infoText .= 'τις προδιαγραφές και τις τιμές, για τα οχήματα που περιγράφονται και παρουσιάζονται στην ιστοσελίδα μας, οποιαδήποτε στιγμή.';
$infoText .= 'Οι τιμές είναι ενδεικτικές.';													
?>
<li class="hover" id="nsmn-vehicles">
	<a href="#"><span>ΜΟΝΤΕΛΑ</span></a>
	<div class="nsmn-layer" id="nsmn-vehicles-list"
	style="width: auto; top: 31px;">
		<div class="content-list">
			<ul class="nsnmn-tab-controller" id=
			"nsmnm-tab-1">
				<li class="active">
					<a href=
					"#nsnmn-passengers-cars-cars">ΕΠΙΒΑΤΙΚΑ</a>

					<div class="hiddenImportant"></div>
				</li>

				<li class="">
					<a href=
					"#nsnmn-commercial-cars">ΕΠΑΓΓΕΛΜΑΤΙΚΑ</a>

					<div class="hiddenImportant"></div>
				</li>
			</ul>

			<div class="vehicles" id=
			"nsnmn-passengers-cars-cars">
				<div>
					<ul class="nsnmn-tab-content">
						<li class="line-cars">
							<ul>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/micra.html'); ?>"> <img width="119" height="62" class=
									"img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/new-micra.png'); ?>"
									style="display: inline;">
									<span class="nsnmn-item-title">MICRA</span> 
									<span class="nsnmn-item-price">Από
										&euro;9.990</span>
										</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?></span></a>
								</li>

								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/note.html'); ?>"><img width="103" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/newNOTE copie.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">NEO NOTE</span> 
										<span class="nsnmn-item-price">Από
											&euro;12.990</span>
									</a>
									<a class=
									"nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?> </span></a>
								</li>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/pulsar.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/Pulsar2_119x62_.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">NEO PULSAR</span> 
										<span class="nsnmn-item-price">Από
											&euro;14.990</span>
									</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?></span></a>
								</li>

								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/juke.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this-> baseUrl('skin/images/navigation/newjuke.png')?>" style="display: inline;">
										<span class="nsnmn-item-title">NEO JUKE</span> 
										<span class="nsnmn-item-price">Από
											&euro;15.400</span>
									</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?> </span></a>
								</li>

								<li class="last-car">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/juke-nismo.html'); ?>"> <img width="119" height="62"class="img-picto" src="<?php echo $this->baseUrl('media/models/juke-nismo/menu/mn_juke.png')?>" style="display: inline;">
										<span class="nsnmn-item-title">NISMO JUKE</span> 
										<span class="nsnmn-item-price">Από
										&euro;28.150</span>
									</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?> </span></a>
								</li>

							</ul>
						</li>

						<li class="line-cars">
							<ul>
								<li>
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/qashqai.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/new-qashqai.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">NEO
										QASHQAI</span> 
										<span class="nsnmn-item-price">Από
										&euro;18.990</span>
									</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?> </span> </a>
								</li>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/xtrail.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/new_x-trail.png'); ?>" style="display: inline;">
									<span class="nsnmn-item-title">X-TRAIL</span> 
									<span class="nsnmn-item-price">Από
										&euro;31.550</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span></a>
								</li>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/370z.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/370z.png'); ?>" style="display: inline;">
									<span class="nsnmn-item-title">370z</span> 
									<!--<span class="nsnmn-item-price">Από
										&euro;67.180</span>-->
									</a>	
									<!--<a class="nsnmn-tooltip"> <span class="after"> Σύμφωνα με την πολιτική της εταιρείας περί συνεχούς βελτίωσης των προϊόντων της, η NISSAN διατηρεί το δικαίωμα να αλλάξει
										τις προδιαγραφές και τις τιμές, για τα οχήματα που περιγράφονται και παρουσιάζονται στην ιστοσελίδα μας, οποιαδήποτε στιγμή.
										Οι τιμές είναι ενδεικτικές και συμπεριλαμβάνουν το όφελος της κρατικής απόσυρσης. </span></a>-->
								</li>

								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/370z-roadster.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/370z-roadster.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">370z-roadster</span> 
										<!--<span class="nsnmn-item-price">Από
											&euro;85.780</span>-->
									</a>	
									<!--<a class="nsnmn-tooltip">
										<span class="after"> </span>
									</a>-->
								</li>

								<li class="last-car">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/gtr.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/GT-R_MY14_Header_119x62.png'); ?>"style="display: inline;">
										<span class="nsnmn-item-title">ΝΕΟ GT-R</span> 
										<!--<span class="nsnmn-item-price">Από
										&euro;157.000</span>-->
									</a>
									<!--<a class="nsnmn-tooltip"> <span class="after"> Σύμφωνα με την πολιτική της εταιρείας περί συνεχούς βελτίωσης των προϊόντων της, η NISSAN διατηρεί το δικαίωμα να αλλάξει
										τις προδιαγραφές και τις τιμές, για τα οχήματα που περιγράφονται και παρουσιάζονται στην ιστοσελίδα μας, οποιαδήποτε στιγμή.
										Οι τιμές είναι ενδεικτικές και συμπεριλαμβάνουν το όφελος της κρατικής απόσυρσης. </span> </a>-->
								</li>
							</ul>
						</li>

						<li class="line-cars">
							<ul>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/city-cars/evalia.html'); ?>"> <img width="119" height="62" class=
									"img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/NV200-combi-big.png'); ?>"style="display: inline;">
										<span class="nsnmn-item-title">EVALIA</span> 
										<span class="nsnmn-item-price">Από
											&euro;19.980</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span> </a>
								</li>
							</ul>
						</li>
					</ul>
				</div>

				<div class="aside">
					<p class="nsnmn-list-ttl"></p>
					<ul>
						<!--
						<li><span><a href="#"
						target="_blank">ΠΡΟΣΦΟΡΕΣ</a></span>
						</li>
						<li><span><a href="#" target="_blank">ΑΝΤΑΛΑΚΤΙΚΑ &amp; ΑΞΕΣΟΥΑΡ</a></span>
						</li>
						<li><span><a href="#" target="_blank">BUSINESS &amp;
						FLEET</a></span>
						</li>
						-->
					</ul>
				</div>
			</div>

			<div class="hidden" id="nsnmn-commercial-cars">
				<div>
					<ul class="nsnmn-tab-content">
						<li class="line-cars">
							<ul>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/np300.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('media/models/np300/menu/menu-np300-navara.png'); ?>" style="display: inline;"> 
										<span class="nsnmn-item-title">NP300 NAVARA</span> 
										<span class="nsnmn-item-price">Από &euro;27.330</span> 
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span> </a>
								</li>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/atleon.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin//images/navigation/atleon.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">ATLEON</span> 
										<span class="nsnmn-item-price">Από &euro;37.900</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span> </a>
								</li>
								<!--<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/primastar.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin//images/navigation/Primastar.png'); ?>"style="display: inline;">
										<span class="nsnmn-item-title">PRIMASTAR</span> 
										<span class="nsnmn-item-price">Από
											&euro;23.830</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> Σύμφωνα με την πολιτική της εταιρείας περί συνεχούς βελτίωσης των προϊόντων της, η NISSAN διατηρεί το δικαίωμα να αλλάξει
										τις προδιαγραφές και τις τιμές, για τα οχήματα που περιγράφονται και παρουσιάζονται στην ιστοσελίδα μας, οποιαδήποτε στιγμή.
										Οι τιμές είναι ενδεικτικές και συμπεριλαμβάνουν το όφελος της κρατικής απόσυρσης. </span></a>
								</li>-->
								<li class="last-car">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/nv200.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/NV200.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">NV200</span> 
										<span class="nsnmn-item-price">Από &euro;17.300</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span></a>
								</li>

								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/cabstar.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('skin/images/navigation/NT400-Cabstar.png'); ?>" style="display: inline;">
										<span class="nsnmn-item-title">CABSTAR</span> 
										<span class="nsnmn-item-price">
											Από &euro;27.500</span>
									</a>
									<a class="nsnmn-tooltip"> <span class="after"> <?php echo $infoText;?> </span></a>
								</li>
								<li class="">
									<a href="<?php echo $this -> baseUrl('vehicles/commercial/nv400.html'); ?>"> <img width="119" height="62" class="img-picto" src="<?php echo $this -> baseUrl('media/models/nv400/menu/NV400.png'); ?>"style="display: inline;">
										<span class="nsnmn-item-title">NV400</span> 
										<span class="nsnmn-item-price">Από
											&euro;28.500</span>
									</a>
									<a class="nsnmn-tooltip"><span class="after"> <?php echo $infoText;?> </span></a>
								</li>
							</ul>
						</li>

						<li class="line-cars">
							<ul></ul>
						</li>
					</ul>
				</div>

				<div class="aside">
					<p class="nsnmn-list-ttl"></p>
					<ul>
						<li>
							<span><a href="<?php echo $this -> baseUrl('fleet-department.html'); ?>" target="_self">ΕΤΑΙΡΙΚΕΣ ΠΩΛΗΣΕΙΣ</a></span>
						</li>
						<li>
							<span><a href="<?php echo $this -> baseUrl('lcvs.html'); ?>" target="_self">LCVS</a></span>
						</li>
					</ul>
				</div>
			</div>
			<!--
				<div class="hidden" id="nsnmn-london-taxi-cars">
				<div>
					<ul>
						<li class="">
							<a href="#">
								<img class="img-picto" src="#" style="display: inline;">
								<span class="nsnmn-item-title"><br>NV200 TAXI</span>
								<span class="nsnmn-item-price">No Price	Available</span>
							</a>
						</li>
					</ul>
				</div>
				<div class="aside">
					<p class="nsnmn-list-ttl"></p>
					<ul>
						<li><span><a href="#" target="_blank">ΠΡΟΣΦΟΡΕΣ</a></span></li>
					</ul>
				</div>
			</div> 
			-->
		</div>
		<a class="btn-close" href="#"><img width="22" height="30" alt="close" src="<?php  echo $this -> baseUrl('skin/images/btn-close.png'); ?>"></a>

	</div>
</li>