<li id="nsmn-network">
 <a href="<?php echo $this->baseUrl('nissan-lottery.html'); ?>"><span>ΚΛΗΡΩΣΗ ALL CLEAR SERVICE</span></a>
 <div id="nsmn-network-list" class="nsmn-layer">
     <!--<div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="#"><span>FLEET SALES ΤΜΗΜΑ</span></a>
          </li>
		</div>-->
       <a class="btn-close" href="#"><img alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>"></a>
    </div>
</li>