<li id="nsmn-network">
 <a href="<?php echo $this->baseUrl('network/map.html'); ?>"><span>ΕΞΟΥΣΙΟΔΟΤΗΜΕΝΟ ΔΙΚΤΥΟ</span></a>
 <div id="nsmn-network-list" class="nsmn-layer">
     <!--<div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="#"><span>FLEET SALES ΤΜΗΜΑ</span></a>
          </li>
		</div>-->
       <a class="btn-close" href="#"><img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>"></a>
    </div>
</li>