<li id="nsmn-contactus">
 <a href="#"><span>contact us</span></a>
 <div id="nsmn-contactus-list" class="nsmn-layer">
  <div class="nsmn-picto-list">
   <ul>
    <li><a href="#"><span>CONTACT US</span></a></li>
    <li><a href="#"><span>CUSTOMER SERVICES</span></a></li>
    <li class="hidden-phone"><a href="#"><span>FREQUENTLY ASKED QUESTIONS</span></a></li>
    <li class="hidden-tablet  hidden-phone"><a href="#"><span>CONFIGURE YOUR NISSAN</span></a></li>
    <li><a href="#"><span>REQUEST A BROCHURE</span></a></li>
    <li><a href="#"><span>BOOK A TEST DRIVE</span></a></li>
    <li><a href="#"><span>FIND A DEALER</span></a></li>
    <li class="hidden-phone"><a href="#"><span>BOOK A SERVICE OR MOT</span></a></li>
   </ul>
  </div>
  <div class="nsmn-picto-list">
   <ul>
    <li><a href="#" target="_blank"><span>YOUTUBE – NISSAN UK</span></a></li>
    <li><a href="#" target="_blank"><span>YOUTUBE - NISMO.TV</span></a></li>
    <li><a href="#" target="_blank"><span>FACEBOOK - NISSAN UK</span></a></li>
    <li><a href="#" target="_blank"><span>FACEBOOK - NISSAN LEAF UK</span></a></li>
    <li><a href="#" target="_blank"><span>TWITTER</span></a></li>
   </ul>
  </div>
 </div>
</li>