<li id="nsmn-mynissan">
 <a href="#"><span>ΤΟ NISSAN ΜΟΥ</span></a>
 <div id="nsmn-mynissan-list" class="nsmn-layer">
 <div class="nsmn-picto-list">
        <ul>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan.html'); ?>"><span>ΤΟ NISSAN ΜΟΥ</span></a>
          </li>
		  <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-warranty.html'); ?>"><span>ΕΓΓΥΗΣΗ NISSAN</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-five-years-warranty.html'); ?>"><span>ΕΓΓΥΗΣΗ 5 ΕΤΩΝ ΣΤΑ ΕΠΑΓΓΕΛΜΑΤΙΚΑ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-car-care.html'); ?>"><span>ΦΡΟΝΤΙΔΑ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-service-care.html'); ?>"><span>ΠΡΟΓΡΑΜΜΑΤΑ ΣΥΝΤΗΡΗΣΗΣ</span></a>
          </li>
          
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-parts-n-accessories.html'); ?>"><span>ΑΝΤΑΛΛΑΚΤΙΚΑ & ΑΞΕΣΟΥΑΡ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-service-advice.html'); ?>"><span>ΣΥΜΒΟΥΛΕΣ ΓΙΑ SERVICE</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-european-service-nissan-program.html'); ?>"><span>ΠΡΟΓΡΑΜΜΑ ΕΞΥΠΗΡΕΤΗΣΗΣ</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-manuals.html'); ?>"><span>ΒΙΒΛΙΑ ΟΔΗΓΙΩΝ ΧΡΗΣΗΣ NISSAN</span></a>
          </li>
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-application-support-used.html'); ?>"><span>ΠΑΡΟΧΗ ΣΤΟΙΧΕΙΩΝ ΓΙΑ ΜΤΧ NISSAN</span></a>
          </li>
          
          <li>
            <a href="<?php  echo $this->baseUrl('my-nissan-faq.html'); ?>"><span>ΣΥΝΗΘΕΙΣ ΕΡΩΤΗΣΕΙΣ</span></a>
          </li>
       </div>
       <a class="btn-close" href="#"><img width="22" height="30" alt="close"src="<?php echo $this->baseUrl('skin/images/btn-close.png'); ?>"></a>
</div>
</li>