<?php echo $this->doctype(); ?>
<html lang="el" class="no-js">
	<head>
		
		<?php 
    	echo $this -> headTitle('Nissan - Νικ. Ι. θεοχαράκης');
		echo $this -> headMeta();
		echo $this -> headLink();
		echo $this -> headScript();
		?>	
	</head>
	<body>
		<script>
		$(function() {
			$( "#tabs" ).tabs();
		});
		</script>
		<!--
		<div id="preloader">
			<div id="status">&nbsp;</div>
		</div>
		-->
		<div id="loader-wrapper">
			<div id="loader"></div>
			<div class="loader-section section-left">
				<img width="89" height="84" src="<?php echo $this->baseUrl('skin/images/mainheadernissanlogo.png');?>" alt="Nissan - Νικ. Ι. Θεοχαράκης ΑΕ"/>
			</div>
			<div class="loader-section section-right"></div>
		</div>
		<div role="main" id="main">
			<?php echo $this->layout()->render('/containers/googleTagManager'); ?>
			<header id="">
				<?php echo $this -> layout() -> render('/sections/header'); ?>
			</header>
			<div id="content">
				<div id="navcontainer">
					<div id="navNumbers" id="step1" data-step="0" class="active">
						<!--1 <font class="styleNavstep">ΔΙΑΜΟΡΦΩΣΗ</font>-->
						<img width="158" height="69" style="display:none;" src="<?php echo $this->baseUrl('skin/images/builder/001up.jpg'); ?>" />
						<img width="158" height="69" src="<?php echo $this->baseUrl('skin/images/builder/001over.jpg'); ?>" />
					</div>
					<div id="navNumbers1" class="step2" data-step="1">
						<!--2 <font class="styleNavstep">ΧΡΩΜΑΤΑ &amp; ΤΑΠΕΤΣΑΡΙΕΣ</font>-->
						<img width="222" height="69"  src="<?php echo $this->baseUrl('skin/images/builder/002up.jpg'); ?>" />
						<img width="222" height="69"  style="display:none;" src="<?php echo $this->baseUrl('skin/images/builder/002over.jpg'); ?>" />
					</div>
					<div id="navNumbers2" class="step3" data-step="2">
						<!--3 <font class="styleNavstep">ΕΞΟΠΛΙΣΜΟΣ &amp; ΑΞΕΣΟΥΑΡ</font>-->
						<img width="222" height="69" src="<?php echo $this->baseUrl('skin/images/builder/003up.jpg'); ?>" />
						<img width="222" height="69" style="display:none;" src="<?php echo $this->baseUrl('skin/images/builder/003over.jpg'); ?>" />
					</div>
					<div id="navNumbers3" class="step4" data-step="3">
						<!--4 <font class="styleNavstep">ΠΕΡΙΛΗΨΗ</font>-->
						<img width="130" height="69" src="<?php echo $this->baseUrl('skin/images/builder/004up.jpg'); ?>" />
						<img width="130" height="69" style="display:none;" src="<?php echo $this->baseUrl('skin/images/builder/004over.jpg'); ?>" />
					</div>
					<!--
					<div style="" class="nav">
						<ul id="details">
							<li style="float:right !important;" class="hover" id="details">
								<a style="text-transform:none !important;" href="#nsmn-details-list">
									<span>Δειτε λεπτομερειες</span>
								</a>
								<div class="nsmn-layer" id="nsmn-details-list" style="width: auto; top: 31px; box-shadow:#999 inset;">
									<div class="content-list"></div>
								</div>
							</li>
							<a class="btn-close" href="#">
								<img alt="close" src="images/btn-close.png">
							</a>
						</ul>
					</div>
					-->
					<div class="right">
						<div class="leftEnd"></div>
						<div class="rightEnd"></div>
						<div class="infoModelColorNameNav"></div>
						<!--
						<div class="infoModelColorNav"></div>
						-->
						<h1 class="grade"></h1>
						<h1 class="nav2"></h1>
						<h2 class="nav4"></h2>
					</div>
				</div>
			</div>
			<div id="columns">
				<?php echo $this->layout()->content;?>
			</div>
		</div>
		<div class="footerPage page">
			<?php echo $this -> layout() -> render('/sections/footer'); ?>
		</div>
		
		<?php echo $this->layout()->render('/containers/googleConversion'); ?>
	</body>
</html>
