<?php echo $this->doctype(); ?>
<html lang="el" class="no-js" ng-app="myApp">
	<head>
	<?php 
	echo $this -> headTitle('Nissan - Νικ. Ι. θεοχαράκης');
	echo $this -> headMeta();
	echo $this -> headLink();
	echo $this -> headScript();
	?>	
	</head>
	
	<body id="myprintpage" data-loading>
		<div id="loader-wrapper">
			<div id="loader"></div>
			<div class="loader-section section-left">
				<img width="89" height="84" src="<?php echo $this->baseurl('skin/images/mainheadernissanlogo.png');?>" alt="nissan - νικ. ι. θεοχαράκης αε"/>
			</div>
			<div class="loader-section section-right"></div>
		</div>		
		<?php echo $this->layout()->content;?>
	</body>  
	<div class="footerPage page">
		<?php //echo $this -> layout() -> render('/sections/footer'); ?>
	</div>
		<?php echo $this->layout()->render('/containers/googleConversion'); ?>
	</body>
</html>
